name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: make docker-build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          make docker-push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull avvero/devirium-bot:latest
            docker stop devirium-bot || true
            docker rm devirium-bot || true
            docker run -d --name devirium-bot -p 8067:8080 \
              -e telegram_token=${{ secrets.TELEGRAM_TOKEN }} \
              -e devirium_chatId=${{ secrets.DEVIRIUM_CHAT_ID }} \
              -e devirium_gardenerChatId=${{ secrets.GARDENER_CHAT_ID }} \
              -e devirium_link=${{ secrets.DEVIRIUM_LINK }} \
              -e openai_token=${{ secrets.OPENAI_TOKEN }} \
              -e corrector_prompt='${{ secrets.CORRECTOR_PROMPT }}' \
              avvero/devirium-bot:latest
